---
title: "EDS 212 Day 4 Comp 4"
format: html
editor: visual
---

## Create vectors

```{r}
rain <- c(3, 5, 10.1, 6)

rain_scaled <- 5 * rain
```

## Create matrices

```{r}
# make one long vector, then wrap into a matrix row by row

my_values <- seq(from = 1, to = 10)

my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)
```

```{r}
# since matrix is not exact multiple lengths of sequence, it starts repeating sequence to fill in gaps
my_matrix2 <- matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)
```

```{r}
# return after every comma for better readability
matrixA <- matrix(data = seq(from = 2, 
                             to = 5, 
                             length = 10), 
                  nrow = 2, 
                  ncol = 5, 
                  byrow = TRUE)
```

```{r}
# matrix math!
# same dimensions so we can add/subtract
my_matrix + matrixA
```

## Matrix Multiplication

```{r}
cats <- matrix(data = c(0, 4, 3, 1), nrow = 2, ncol = 2, byrow = TRUE)

dogs <- matrix(data = c(6, -3, 0, 2), nrow = 2, ncol = 2, byrow = TRUE)
```

```{r}
# multiply with dot product
dogs %*% cats
```

## Leslie Matrix Example

```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), 
                        nrow = 3, 
                        ncol = 3, 
                        byrow = TRUE)


insect_y0 <- c(12000, 700, 500)
```

Find the population structure for each life stage at t = 1 year:

```{r}
# R treats vector as matrix with single column, three rows
insect_y1 <- insect_leslie %*% insect_y0
```

Find the population structure at t = 2 years:

```{r}
insect_y2 <- insect_leslie %*% insect_y1
```
